"""Add gsc and ga4 fields to projects

Revision ID: 85549a0ec127
Revises: 975e377152a2
Create Date: 2026-02-23 09:44:13.824375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85549a0ec127'
down_revision: Union[str, None] = '975e377152a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('gsc_url', sa.String(length=255), nullable=True))
    op.add_column('projects', sa.Column('ga4_property_id', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'ga4_property_id')
    op.drop_column('projects', 'gsc_url')
    # ### end Alembic commands ###
