"""audit_remediation_models

Revision ID: ad7ddd307f60
Revises: b7f3c2c61d1a
Create Date: 2026-02-27 07:23:23.670363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ad7ddd307f60'
down_revision: Union[str, None] = 'b7f3c2c61d1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_advisor_ai_brief_payloads_brief_id'), 'advisor_ai_brief_payloads', ['brief_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_communication_logs_client_id'), 'communication_logs', ['client_id'], unique=False)
    op.create_index(op.f('ix_communication_logs_contact_id'), 'communication_logs', ['contact_id'], unique=False)
    op.create_index(op.f('ix_communication_logs_user_id'), 'communication_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_daily_updates_user_id'), 'daily_updates', ['user_id'], unique=False)
    op.create_index(op.f('ix_events_client_id'), 'events', ['client_id'], unique=False)
    op.create_index(op.f('ix_events_project_id'), 'events', ['project_id'], unique=False)
    op.create_index(op.f('ix_events_user_id'), 'events', ['user_id'], unique=False)
    op.create_index(op.f('ix_expenses_category_id'), 'expenses', ['category_id'], unique=False)
    op.create_index(op.f('ix_generated_reports_client_id'), 'generated_reports', ['client_id'], unique=False)
    op.create_index(op.f('ix_generated_reports_project_id'), 'generated_reports', ['project_id'], unique=False)
    op.create_index(op.f('ix_generated_reports_user_id'), 'generated_reports', ['user_id'], unique=False)
    op.create_index(op.f('ix_growth_ideas_project_id'), 'growth_ideas', ['project_id'], unique=False)
    op.create_index(op.f('ix_growth_ideas_task_id'), 'growth_ideas', ['task_id'], unique=False)
    op.create_index(op.f('ix_holded_invoices_cache_client_id'), 'holded_invoices_cache', ['client_id'], unique=False)
    op.create_index(op.f('ix_income_client_id'), 'income', ['client_id'], unique=False)
    op.create_index(op.f('ix_invoice_items_invoice_id'), 'invoice_items', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_invoice_items_task_id'), 'invoice_items', ['task_id'], unique=False)
    op.create_index(op.f('ix_invoices_client_id'), 'invoices', ['client_id'], unique=False)
    op.create_index(op.f('ix_lead_activities_lead_id'), 'lead_activities', ['lead_id'], unique=False)
    op.create_index(op.f('ix_lead_activities_user_id'), 'lead_activities', ['user_id'], unique=False)
    op.create_index(op.f('ix_leads_assigned_to'), 'leads', ['assigned_to'], unique=False)
    op.create_index(op.f('ix_leads_converted_client_id'), 'leads', ['converted_client_id'], unique=False)
    op.create_index(op.f('ix_pm_insights_client_id'), 'pm_insights', ['client_id'], unique=False)
    op.create_index(op.f('ix_pm_insights_project_id'), 'pm_insights', ['project_id'], unique=False)
    op.create_index(op.f('ix_pm_insights_task_id'), 'pm_insights', ['task_id'], unique=False)
    op.create_index(op.f('ix_pm_insights_user_id'), 'pm_insights', ['user_id'], unique=False)
    op.create_index(op.f('ix_project_phases_project_id'), 'project_phases', ['project_id'], unique=False)
    op.create_index(op.f('ix_projects_client_id'), 'projects', ['client_id'], unique=False)
    op.alter_column('proposals', 'title',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=300),
               existing_nullable=False)
    # NOTE: Keeping JSONB in DB (superior to JSON for PostgreSQL).
    # NOTE: Keeping TIMESTAMP for valid_until to avoid data loss.
    # Model uses JSON/Date but DB types are functionally compatible.
    op.create_index(op.f('ix_proposals_client_id'), 'proposals', ['client_id'], unique=False)
    op.create_index(op.f('ix_proposals_converted_project_id'), 'proposals', ['converted_project_id'], unique=False)
    op.create_index(op.f('ix_proposals_created_by'), 'proposals', ['created_by'], unique=False)
    op.create_index(op.f('ix_proposals_lead_id'), 'proposals', ['lead_id'], unique=False)
    op.drop_constraint('proposals_project_id_fkey', 'proposals', type_='foreignkey')
    op.drop_column('proposals', 'project_id')
    op.create_index(op.f('ix_tasks_assigned_to'), 'tasks', ['assigned_to'], unique=False)
    op.create_index(op.f('ix_tasks_category_id'), 'tasks', ['category_id'], unique=False)
    op.create_index(op.f('ix_tasks_client_id'), 'tasks', ['client_id'], unique=False)
    op.create_index(op.f('ix_tasks_depends_on'), 'tasks', ['depends_on'], unique=False)
    op.create_index(op.f('ix_tasks_phase_id'), 'tasks', ['phase_id'], unique=False)
    op.create_index(op.f('ix_tasks_project_id'), 'tasks', ['project_id'], unique=False)
    op.create_index(op.f('ix_time_entries_task_id'), 'time_entries', ['task_id'], unique=False)
    op.create_index(op.f('ix_time_entries_user_id'), 'time_entries', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_invitations_invited_by'), 'user_invitations', ['invited_by'], unique=False)
    op.create_index(op.f('ix_user_permissions_user_id'), 'user_permissions', ['user_id'], unique=False)
    op.create_index(op.f('ix_users_invited_by'), 'users', ['invited_by'], unique=False)
    op.create_index(op.f('ix_weekly_digests_client_id'), 'weekly_digests', ['client_id'], unique=False)
    op.create_index(op.f('ix_weekly_digests_created_by'), 'weekly_digests', ['created_by'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weekly_digests_created_by'), table_name='weekly_digests')
    op.drop_index(op.f('ix_weekly_digests_client_id'), table_name='weekly_digests')
    op.drop_index(op.f('ix_users_invited_by'), table_name='users')
    op.drop_index(op.f('ix_user_permissions_user_id'), table_name='user_permissions')
    op.drop_index(op.f('ix_user_invitations_invited_by'), table_name='user_invitations')
    op.drop_index(op.f('ix_time_entries_user_id'), table_name='time_entries')
    op.drop_index(op.f('ix_time_entries_task_id'), table_name='time_entries')
    op.drop_index(op.f('ix_tasks_project_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_phase_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_depends_on'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_client_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_category_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_assigned_to'), table_name='tasks')
    op.add_column('proposals', sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('proposals_project_id_fkey', 'proposals', 'projects', ['project_id'], ['id'])
    op.drop_index(op.f('ix_proposals_lead_id'), table_name='proposals')
    op.drop_index(op.f('ix_proposals_created_by'), table_name='proposals')
    op.drop_index(op.f('ix_proposals_converted_project_id'), table_name='proposals')
    op.drop_index(op.f('ix_proposals_client_id'), table_name='proposals')
    # NOTE: JSONB/TIMESTAMP kept as-is (see upgrade note)
    op.alter_column('proposals', 'title',
               existing_type=sa.String(length=300),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
    op.drop_index(op.f('ix_projects_client_id'), table_name='projects')
    op.drop_index(op.f('ix_project_phases_project_id'), table_name='project_phases')
    op.drop_index(op.f('ix_pm_insights_user_id'), table_name='pm_insights')
    op.drop_index(op.f('ix_pm_insights_task_id'), table_name='pm_insights')
    op.drop_index(op.f('ix_pm_insights_project_id'), table_name='pm_insights')
    op.drop_index(op.f('ix_pm_insights_client_id'), table_name='pm_insights')
    op.drop_index(op.f('ix_leads_converted_client_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_assigned_to'), table_name='leads')
    op.drop_index(op.f('ix_lead_activities_user_id'), table_name='lead_activities')
    op.drop_index(op.f('ix_lead_activities_lead_id'), table_name='lead_activities')
    op.drop_index(op.f('ix_invoices_client_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoice_items_task_id'), table_name='invoice_items')
    op.drop_index(op.f('ix_invoice_items_invoice_id'), table_name='invoice_items')
    op.drop_index(op.f('ix_income_client_id'), table_name='income')
    op.drop_index(op.f('ix_holded_invoices_cache_client_id'), table_name='holded_invoices_cache')
    op.drop_index(op.f('ix_growth_ideas_task_id'), table_name='growth_ideas')
    op.drop_index(op.f('ix_growth_ideas_project_id'), table_name='growth_ideas')
    op.drop_index(op.f('ix_generated_reports_user_id'), table_name='generated_reports')
    op.drop_index(op.f('ix_generated_reports_project_id'), table_name='generated_reports')
    op.drop_index(op.f('ix_generated_reports_client_id'), table_name='generated_reports')
    op.drop_index(op.f('ix_expenses_category_id'), table_name='expenses')
    op.drop_index(op.f('ix_events_user_id'), table_name='events')
    op.drop_index(op.f('ix_events_project_id'), table_name='events')
    op.drop_index(op.f('ix_events_client_id'), table_name='events')
    op.drop_index(op.f('ix_daily_updates_user_id'), table_name='daily_updates')
    op.drop_index(op.f('ix_communication_logs_user_id'), table_name='communication_logs')
    op.drop_index(op.f('ix_communication_logs_contact_id'), table_name='communication_logs')
    op.drop_index(op.f('ix_communication_logs_client_id'), table_name='communication_logs')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_advisor_ai_brief_payloads_brief_id'), table_name='advisor_ai_brief_payloads')
    # ### end Alembic commands ###
