"""Add quality insight type

Revision ID: c5ed1dc5fc22
Revises: cf31d16504bf
Create Date: 2026-02-24 06:57:31.050046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5ed1dc5fc22'
down_revision: Union[str, None] = 'cf31d16504bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
