import { fireEvent, render, screen, waitFor } from "@testing-library/react"
import { QueryClient, QueryClientProvider } from "@tanstack/react-query"
import { MemoryRouter } from "react-router-dom"
import { beforeEach, expect, it, vi } from "vitest"
import DailysPage from "./dailys-page"

const mocks = vi.hoisted(() => ({ list: vi.fn(), forDate: vi.fn(), prefill: vi.fn(), submit: vi.fn(), edit: vi.fn(), reparse: vi.fn(), del: vi.fn(), send: vi.fn(), toastError: vi.fn(), userId: 7, canReadTasks: true }))
vi.mock("@/lib/api", () => ({ dailysApi: { list: mocks.list, forDate: mocks.forDate, prefill: mocks.prefill, submit: mocks.submit, edit: mocks.edit, reparse: mocks.reparse, delete: mocks.del, sendDiscord: mocks.send } }))
vi.mock("@/context/auth-context", () => ({ useAuth: () => ({ user: { id: mocks.userId, role: "member" }, hasPermission: (permission: string) => permission !== "tasks" || mocks.canReadTasks }) }))
vi.mock("@/hooks/use-business-date", () => ({ useBusinessDate: () => "2026-09-20" }))
vi.mock("@/components/delivery-receipts", () => ({ DeliveryReceipts: () => <div>Recibos</div>, deliveryToast: vi.fn() }))
vi.mock("@/components/ui/confirm-dialog", () => ({ ConfirmDialog: () => null }))
vi.mock("sonner", () => ({ toast: { success: vi.fn(), error: mocks.toastError } }))
const daily = (overrides = {}) => ({ id: 4, user_id: 7, user_name: "Ana", date: "2026-09-20", raw_text: "Guardado", parsed_data: null, status: "draft", discord_sent_at: null, revision: 3, source_facts: [], created_at: "2026-09-20T10:00:00Z", updated_at: "2026-09-20T10:00:00Z", ...overrides })
function setup() { const client = new QueryClient({ defaultOptions: { queries: { retry: false }, mutations: { retry: false } } }); return { client, ...render(<QueryClientProvider client={client}><MemoryRouter><DailysPage /></MemoryRouter></QueryClientProvider>) } }
const notes = () => screen.findByLabelText("Notas del daily")
beforeEach(() => { vi.clearAllMocks(); localStorage.clear(); mocks.userId = 7; mocks.canReadTasks = true; Element.prototype.scrollIntoView = vi.fn(); mocks.list.mockResolvedValue([]); mocks.forDate.mockResolvedValue(null); mocks.prefill.mockResolvedValue({ date: "2026-09-20", text: "", completed_count: 1, worked_on_count: 1, total_minutes: 25, facts: [{ key: "opaque-1", kind: "time_logged", task_id: 8, title: "Revisar portada", client_name: "Acme", project_name: "Web", minutes: 25, href: "/tasks?task=8", detail: "Registrado" }] }); mocks.submit.mockResolvedValue(daily({ source_facts: [{ key: "opaque-1", kind: "time_logged", task_id: 8, title: "Revisar portada", minutes: 25, href: "/tasks?task=8", detail: null }] })) })
it("adds selected facts without replacing notes and saves their opaque keys", async () => {
  setup()
  fireEvent.change(await notes(), { target: { value: "Nota humana" } })
  fireEvent.click(screen.getByRole("button", { name: "Actualizar hechos" }))
  const fact = await screen.findByRole("checkbox", { name: "Revisar portada" })
  fireEvent.click(fact)
  fireEvent.click(screen.getByRole("button", { name: "Añadir hechos seleccionados a las notas" }))
  expect(await notes()).toHaveValue("Nota humana\n\n- Revisar portada — Registrado")
  fireEvent.click(screen.getByRole("button", { name: "Guardar borrador" }))
  await waitFor(() => expect(mocks.submit).toHaveBeenCalledWith({ raw_text: expect.stringContaining("Nota humana"), date: "2026-09-20", source_fact_keys: ["opaque-1"] }))
  expect(mocks.reparse).not.toHaveBeenCalled()
})
it("keeps text edited during an uncertain save and offers conflict recovery", async () => {
  let reject!: (reason: unknown) => void
  mocks.submit.mockReturnValue(new Promise((_resolve, fail) => { reject = fail }))
  setup()
  const field = await notes()
  fireEvent.change(field, { target: { value: "Primera versión" } })
  fireEvent.click(screen.getByRole("button", { name: "Guardar borrador" }))
  fireEvent.change(field, { target: { value: "Texto nuevo que no se pierde" } })
  reject({ response: { data: { detail: { code: "daily_conflict", current: daily({ raw_text: "Otra edición" }) } } } })
  await screen.findByRole("button", { name: "Continuar con mis notas" })
  expect(field).toHaveValue("Texto nuevo que no se pierde")
})
it("keeps newer local notes and the saved revision when a save response arrives late", async () => {
  let resolve!: (value: ReturnType<typeof daily>) => void
  mocks.submit.mockReturnValue(new Promise((done) => { resolve = done }))
  setup()
  const field = await notes()
  fireEvent.change(field, { target: { value: "Versión enviada" } })
  fireEvent.click(screen.getByRole("button", { name: "Guardar borrador" }))
  fireEvent.change(field, { target: { value: "Notas escritas mientras guardaba" } })
  resolve(daily({ raw_text: "Versión enviada", revision: 9 }))
  await waitFor(() => expect(screen.getByRole("button", { name: "Estructurar con IA" })).toBeInTheDocument())
  expect(field).toHaveValue("Notas escritas mientras guardaba")
  expect(JSON.parse(localStorage.getItem("agency:daily-closing:7:2026-09-20") || "{}")).toMatchObject({
    rawText: "Notas escritas mientras guardaba",
    baseId: 4,
    baseRevision: 9,
  })
})
it("does not offer AI structuring for a sent daily", async () => {
  mocks.forDate.mockResolvedValue(daily({ status: "sent" }))
  setup()
  await waitFor(() => expect(mocks.forDate).toHaveBeenCalledWith("2026-09-20"))
  expect(screen.queryByRole("button", { name: "Estructurar con IA" })).not.toBeInTheDocument()
})
it("uses the saved revision only when the user explicitly requests AI structure", async () => {
  mocks.forDate.mockResolvedValue(daily())
  mocks.reparse.mockResolvedValue(daily({ revision: 4 }))
  setup()
  const structure = await screen.findByRole("button", { name: "Estructurar con IA" })
  fireEvent.click(structure)
  await waitFor(() => expect(mocks.reparse).toHaveBeenCalledWith(4, 3))
  expect(mocks.edit).not.toHaveBeenCalled()
})
it("opens a historical daily in its own date without retargeting the active notes", async () => {
  mocks.list.mockResolvedValue([daily({ id: 22, date: "2026-09-19", raw_text: "Histórico", revision: 6 })])
  mocks.forDate.mockImplementation((date: string) => Promise.resolve(date === "2026-09-19" ? daily({ id: 22, date: "2026-09-19", raw_text: "Histórico", revision: 6 }) : null))
  setup()
  fireEvent.change(await notes(), { target: { value: "Notas del 20" } })
  fireEvent.click(await screen.findByRole("button", { name: "Editar" }))
  expect(await screen.findByLabelText("Fecha del daily")).toHaveValue("2026-09-19")
  expect(await notes()).toHaveValue("Histórico")
})
it("keeps local drafts isolated by civil date", async () => {
  localStorage.setItem("agency:daily-closing:7:2026-09-21", JSON.stringify({ rawText: "Notas del día siguiente", sourceFactKeys: ["opaque"], sourceFacts: [], baseId: null, baseRevision: null }))
  setup()
  fireEvent.change(screen.getByLabelText("Fecha del daily"), { target: { value: "2026-09-21" } })
  expect(await screen.findByDisplayValue("Notas del día siguiente")).toBeInTheDocument()
})
it("does not load another actor's local draft after an identity change", async () => {
  const view = setup()
  fireEvent.change(await notes(), { target: { value: "Notas de la usuaria 7" } })
  mocks.userId = 8
  view.rerender(<QueryClientProvider client={view.client}><MemoryRouter><DailysPage /></MemoryRouter></QueryClientProvider>)
  expect(await notes()).toHaveValue("")
  expect(JSON.parse(localStorage.getItem("agency:daily-closing:7:2026-09-20") || "{}")).toMatchObject({ rawText: "Notas de la usuaria 7" })
})
it("does not let a save from an unmounted date overwrite newer notes after returning", async () => {
  let resolve!: (value: ReturnType<typeof daily>) => void
  mocks.submit.mockReturnValue(new Promise((done) => { resolve = done }))
  setup()
  const field = await notes()
  fireEvent.change(field, { target: { value: "Versión antigua" } })
  fireEvent.click(screen.getByRole("button", { name: "Guardar borrador" }))
  fireEvent.change(screen.getByLabelText("Fecha del daily"), { target: { value: "2026-09-21" } })
  await notes()
  fireEvent.change(screen.getByLabelText("Fecha del daily"), { target: { value: "2026-09-20" } })
  const returned = await notes()
  fireEvent.change(returned, { target: { value: "Notas nuevas al volver" } })
  resolve(daily({ raw_text: "Versión antigua", revision: 8 }))
  await waitFor(() => expect(returned).toHaveValue("Notas nuevas al volver"))
  expect(JSON.parse(localStorage.getItem("agency:daily-closing:7:2026-09-20") || "{}")).toMatchObject({ rawText: "Notas nuevas al volver" })
})
it("uses a persisted matching revision as the CAS base after reload", async () => {
  const saved = daily({ revision: 8, raw_text: "Borrador local", source_facts: [{ key: "opaque-1", kind: "time_logged", task_id: 8, title: "Fuente", minutes: 12, href: "/tasks?task=8", detail: null }] })
  localStorage.setItem("agency:daily-closing:7:2026-09-20", JSON.stringify({ rawText: "Borrador local editado", sourceFactKeys: ["opaque-1"], sourceFacts: saved.source_facts, baseId: 4, baseRevision: 8 }))
  mocks.forDate.mockResolvedValue(saved)
  setup()
  fireEvent.click(await screen.findByRole("button", { name: "Guardar borrador" }))
  await waitFor(() => expect(mocks.edit).toHaveBeenCalledWith(4, expect.objectContaining({ revision: 8, raw_text: "Borrador local editado", source_fact_keys: ["opaque-1"] })))
})
it("compares a different saved revision and continues local notes using the current revision", async () => {
  localStorage.setItem("agency:daily-closing:7:2026-09-20", JSON.stringify({ rawText: "Mi versión", sourceFactKeys: [], sourceFacts: [], baseId: 4, baseRevision: 2 }))
  mocks.forDate.mockResolvedValue(daily({ raw_text: "Versión servidor", revision: 5 }))
  setup()
  expect(await screen.findByText("Texto guardado · revisión 5")).toBeInTheDocument()
  fireEvent.click(screen.getByRole("button", { name: "Continuar con mis notas" }))
  fireEvent.click(screen.getByRole("button", { name: "Guardar borrador" }))
  await waitFor(() => expect(mocks.edit).toHaveBeenCalledWith(4, expect.objectContaining({ revision: 5, raw_text: "Mi versión" })))
})
it("does not expose stored task links when current task access is absent", async () => {
  mocks.canReadTasks = false
  setup()
  fireEvent.click(await screen.findByRole("button", { name: "Actualizar hechos" }))
  expect(await screen.findByText("Revisar portada")).not.toHaveAttribute("href")
})
it("blocks current history actions until a local draft chooses between it and an existing server version", async () => {
  localStorage.setItem("agency:daily-closing:7:2026-09-20", JSON.stringify({ rawText: "Notas sin base", sourceFactKeys: [], sourceFacts: [], baseId: null, baseRevision: null }))
  const saved = daily({ revision: 5 })
  mocks.forDate.mockResolvedValue(saved)
  mocks.list.mockResolvedValue([saved])
  setup()
  await screen.findByText("Texto guardado · revisión 5")
  expect(screen.getByRole("button", { name: "Guardar borrador" })).toBeDisabled()
  expect(await screen.findByRole("button", { name: "Enviar a Discord" })).toBeDisabled()
  expect(screen.getByRole("button", { name: "Eliminar" })).toBeDisabled()
})
it("unblocks a saved version only after a successful check following an uncertain AI request", async () => {
  const saved = daily({ revision: 5 })
  mocks.forDate.mockResolvedValue(saved)
  mocks.list.mockResolvedValue([saved])
  mocks.reparse.mockRejectedValue({ response: { status: 502 } })
  setup()
  fireEvent.click(await screen.findByRole("button", { name: "Estructurar con IA" }))
  const retry = await screen.findByRole("button", { name: "Reintentar" })
  expect(await screen.findByRole("button", { name: "Enviar a Discord" })).toBeDisabled()
  fireEvent.click(retry)
  await waitFor(() => expect(screen.getByRole("button", { name: "Enviar a Discord" })).toBeEnabled())
})
it("keeps the saved version blocked when the uncertainty check fails", async () => {
  const saved = daily({ revision: 5 })
  mocks.forDate.mockResolvedValue(saved)
  mocks.list.mockResolvedValue([saved])
  mocks.reparse.mockRejectedValue({ response: { status: 502 } })
  setup()
  fireEvent.click(await screen.findByRole("button", { name: "Estructurar con IA" }))
  await screen.findByRole("button", { name: "Reintentar" })
  mocks.forDate.mockRejectedValue(new Error("offline"))
  fireEvent.click(screen.getByRole("button", { name: "Reintentar" }))
  await waitFor(() => expect(screen.getByRole("button", { name: "Enviar a Discord" })).toBeDisabled())
})
it("does not accept a late save response that would downgrade a newer refetched revision", async () => {
  let resolve!: (value: ReturnType<typeof daily>) => void
  const revision1 = daily({ revision: 1, raw_text: "Servidor rev 1" })
  const revision3 = daily({ revision: 3, raw_text: "Servidor rev 3" })
  mocks.forDate.mockResolvedValue(revision1)
  mocks.edit.mockReturnValue(new Promise((done) => { resolve = done }))
  const view = setup()
  fireEvent.change(await notes(), { target: { value: "Mi cambio rev 1" } })
  fireEvent.click(screen.getByRole("button", { name: "Guardar borrador" }))
  view.client.setQueryData(["dailys", 7, "for-date", "2026-09-20"], revision3)
  expect(await screen.findByText("Texto guardado · revisión 3")).toBeInTheDocument()
  resolve(daily({ revision: 2, raw_text: "Respuesta tardía rev 2" }))
  await waitFor(() => expect(screen.getByText("Texto guardado · revisión 3")).toBeInTheDocument())
  expect(screen.getByRole("button", { name: "Continuar con mis notas" })).toBeInTheDocument()
})
it("retains selected fact snapshots across refresh and a full remount", async () => {
  const saved = daily({ revision: 4 })
  mocks.forDate.mockResolvedValue(saved)
  const selected = { key: "opaque-selected", kind: "time_logged", task_id: 8, title: "Fuente retenida", minutes: 25, href: "/tasks?task=8", detail: "Registrado" }
  mocks.prefill.mockResolvedValueOnce({ date: "2026-09-20", text: "", completed_count: 0, worked_on_count: 1, total_minutes: 25, facts: [selected] })
  const first = setup()
  fireEvent.click(await screen.findByRole("button", { name: "Actualizar hechos" }))
  fireEvent.click(await screen.findByRole("checkbox", { name: "Fuente retenida" }))
  mocks.prefill.mockResolvedValueOnce({ date: "2026-09-20", text: "", completed_count: 0, worked_on_count: 0, total_minutes: 0, facts: [] })
  fireEvent.click(screen.getByRole("button", { name: "Actualizar hechos" }))
  expect(await screen.findByRole("checkbox", { name: "Fuente retenida" })).toBeChecked()
  first.unmount()
  setup()
  expect(await screen.findByRole("checkbox", { name: "Fuente retenida" })).toBeChecked()
})
it("shows a human 409 message instead of serializing the conflict payload", async () => {
  const rawPayload = "{\"current\":\"payload-private-very-long\"}"
  mocks.submit.mockRejectedValue({ response: { status: 409, data: { detail: { code: "daily_conflict", message: "El resumen cambió; revisa la versión guardada.", current: daily({ raw_text: rawPayload }) } } } })
  setup()
  fireEvent.change(await notes(), { target: { value: "Texto local" } })
  fireEvent.click(screen.getByRole("button", { name: "Guardar borrador" }))
  await screen.findByRole("button", { name: "Continuar con mis notas" })
  expect(mocks.toastError).toHaveBeenCalledWith("El resumen cambió; revisa la versión guardada.")
  expect(mocks.toastError).not.toHaveBeenCalledWith(expect.stringContaining("payload-private-very-long"))
})
